default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chile_temple_development
  host: localhost
  username: developer

test:
  <<: *default
  database: chile_temple_test
  host: localhost
  username: developer

production:
  <<: *default
  database: db/production.sqlite3
